import type { BatchPreview } from './types'

export const demoPreview: BatchPreview = {
  Action: 'Preview',
  ApprovalType: 'Cloud',
  ExecutionMode: 'Approval',
  DefinitionName: '【测试】云账户批量付款资源（仅达人）',
  AutoSubmitEnabled: true,
  RecordCount: 3,
  TotalAmount: 18650,
  ApprovalAmount: 19890.23,
  ServiceFeeRate: 0.0665,
  CanSubmit: true,
  BlockingErrors: [],
  Errors: [],
  RequiredUploads: [],
  Records: [
    {
      RecordId: 'demo-001',
      Name: '小红书达人首发内容',
      ProjectName: '百田森夏季内容项目',
      ProjectCode: 'PRJ-2026-0712',
      PaymentEntity: '游鸟',
      ResourceAccount: '森屿内容工作室',
      Recipient: '林晓楠',
      PaymentMethod: '云账户支付',
      Cost: 6800,
      AcceptanceStatus: '已验收',
      ContractStatus: '已签署',
      InvoiceStatus: '无需发票',
      AttachmentCount: 2,
      Platform: '小红书',
      Account: '森屿内容工作室',
      Topic: '夏季穿搭内容首发',
      Link: 'https://example.com/post/1',
      TaxRate: '6%',
      PayeeAccountName: null,
      PayeeAccountNumber: null,
      BankName: null,
      BankBranch: null,
      Province: null,
      City: null,
      AccountType: null,
      ProjectLinked: true,
      ResourceLinked: true,
      Errors: [],
    },
    {
      RecordId: 'demo-002',
      Name: '抖音达人短视频发布',
      ProjectName: '百田森夏季内容项目',
      ProjectCode: 'PRJ-2026-0712',
      PaymentEntity: '游鸟',
      ResourceAccount: '森屿内容工作室',
      Recipient: '林晓楠',
      PaymentMethod: '云账户支付',
      Cost: 7200,
      AcceptanceStatus: '已验收',
      ContractStatus: '已签署',
      InvoiceStatus: '无需发票',
      AttachmentCount: 3,
      Platform: '抖音',
      Account: '森屿内容工作室',
      Topic: '夏季短视频',
      Link: 'https://example.com/post/2',
      TaxRate: '6%',
      PayeeAccountName: null,
      PayeeAccountNumber: null,
      BankName: null,
      BankBranch: null,
      Province: null,
      City: null,
      AccountType: null,
      ProjectLinked: true,
      ResourceLinked: true,
      Errors: [],
    },
    {
      RecordId: 'demo-003',
      Name: '素材授权及二次分发',
      ProjectName: '百田森夏季内容项目',
      ProjectCode: 'PRJ-2026-0712',
      PaymentEntity: '游鸟',
      ResourceAccount: '森屿内容工作室',
      Recipient: '林晓楠',
      PaymentMethod: '云账户支付',
      Cost: 4650,
      AcceptanceStatus: '已验收',
      ContractStatus: '无需合同',
      InvoiceStatus: '已审核',
      AttachmentCount: 1,
      Platform: '其他',
      Account: '森屿内容工作室',
      Topic: '素材授权',
      Link: 'https://example.com/post/3',
      TaxRate: '6%',
      PayeeAccountName: null,
      PayeeAccountNumber: null,
      BankName: null,
      BankBranch: null,
      Province: null,
      City: null,
      AccountType: null,
      ProjectLinked: true,
      ResourceLinked: true,
      Errors: [],
    },
  ],
}
