import type { BatchPreview } from './types'

export const demoPreview: BatchPreview = {
  Action: 'Preview',
  ApprovalType: 'Cloud',
  ExecutionMode: 'Approval',
  DefinitionName: '✳️【其他】供应商云账户付款【多收款人】',
  AutoSubmitEnabled: true,
  RecordCount: 3,
  TotalAmount: 18650,
  CanSubmit: true,
  Errors: [],
  Records: [
    {
      RecordId: 'demo-001',
      Name: '小红书达人首发内容',
      ProjectName: '百田森夏季内容项目',
      ProjectCode: 'PRJ-2026-0712',
      ResourceAccount: '森屿内容工作室',
      Recipient: '林晓楠',
      PaymentMethod: '云账户支付',
      Cost: 6800,
      AcceptanceStatus: '已验收',
      ContractStatus: '已签署',
      InvoiceStatus: '无需发票',
      AttachmentCount: 2,
      ProjectLinked: true,
      ResourceLinked: true,
      Errors: [],
    },
    {
      RecordId: 'demo-002',
      Name: '抖音达人短视频发布',
      ProjectName: '百田森夏季内容项目',
      ProjectCode: 'PRJ-2026-0712',
      ResourceAccount: '森屿内容工作室',
      Recipient: '林晓楠',
      PaymentMethod: '云账户支付',
      Cost: 7200,
      AcceptanceStatus: '已验收',
      ContractStatus: '已签署',
      InvoiceStatus: '无需发票',
      AttachmentCount: 3,
      ProjectLinked: true,
      ResourceLinked: true,
      Errors: [],
    },
    {
      RecordId: 'demo-003',
      Name: '素材授权及二次分发',
      ProjectName: '百田森夏季内容项目',
      ProjectCode: 'PRJ-2026-0712',
      ResourceAccount: '森屿内容工作室',
      Recipient: '林晓楠',
      PaymentMethod: '云账户支付',
      Cost: 4650,
      AcceptanceStatus: '已验收',
      ContractStatus: '无需合同',
      InvoiceStatus: '已审核',
      AttachmentCount: 1,
      ProjectLinked: true,
      ResourceLinked: true,
      Errors: [],
    },
  ],
}
